### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by lianfeng1014** [uilibrary/matx-react#37]
After build, it is not working.

Uncaught SyntaxError: Unexpected token '<'
react-dom.production.min.js:216 ChunkLoadError: Loading chunk 0 failed.
(missing: http://x.x.x.x/session/static/js/0.e4580c46.chunk.js)
    at Function.c.e (VM97:1:3686)
    at SessionRoutes.js:6:38
    at A (react.production.min.js:18:52)
    at Xs (react-dom.production.min.js:269:22)
    at Iu (react-dom.production.min.js:250:347)
    at Tu (react-dom.production.min.js:250:278)
    at ju (react-dom.production.min.js:250:138)
    at bu (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)

**Comment by naime-hossain** [comment]
Please check the latest version
